name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake ninja-build g++ make bc \
            libopenmpi-dev openmpi-bin \
            libyaml-cpp-dev \
            libnetcdf-dev libnetcdf-c++4-dev netcdf-bin

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt gcovr

      - name: Configure
        run: cmake -S . -B build -G Ninja -DBUILD_TESTING=ON -DENABLE_COVERAGE=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Run climate-sim tests
        env:
          OMPI_MCA_btl: "self,tcp"
        run: ctest --test-dir build --output-on-failure

      - name: Generate climate-sim coverage report
        run: |
          mkdir -p coverage
          gcovr --txt

      - name: Run visualization tests with coverage
        run: pytest --cov --cov-fail-under=90

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Archive outputs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-and-results
          path: |
            build/Testing/**/*
            bench/results/*.csv
          if-no-files-found: ignore
